# Generated by Django 4.2.9 on 2024-02-08 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='quntity',
            new_name='quantity',
        ),
    ]
