# Generated by Django 4.2.9 on 2024-03-15 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_products_category_products_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='categories',
            new_name='category',
        ),
    ]
